<?php
declare(strict_types=1);

// RejectionReasonGenerator SDK utility registration

require_once __DIR__ . '/../core/UtilityType.php';
require_once __DIR__ . '/Clean.php';
require_once __DIR__ . '/Done.php';
require_once __DIR__ . '/MakeError.php';
require_once __DIR__ . '/FeatureAdd.php';
require_once __DIR__ . '/FeatureHook.php';
require_once __DIR__ . '/FeatureInit.php';
require_once __DIR__ . '/Fetcher.php';
require_once __DIR__ . '/MakeFetchDef.php';
require_once __DIR__ . '/MakeContext.php';
require_once __DIR__ . '/MakeOptions.php';
require_once __DIR__ . '/MakeRequest.php';
require_once __DIR__ . '/MakeResponse.php';
require_once __DIR__ . '/MakeResult.php';
require_once __DIR__ . '/MakePoint.php';
require_once __DIR__ . '/MakeSpec.php';
require_once __DIR__ . '/MakeUrl.php';
require_once __DIR__ . '/Param.php';
require_once __DIR__ . '/PrepareAuth.php';
require_once __DIR__ . '/PrepareBody.php';
require_once __DIR__ . '/Graphql.php';
require_once __DIR__ . '/PrepareHeaders.php';
require_once __DIR__ . '/PrepareMethod.php';
require_once __DIR__ . '/PrepareParams.php';
require_once __DIR__ . '/PreparePath.php';
require_once __DIR__ . '/PrepareQuery.php';
require_once __DIR__ . '/ResultBasic.php';
require_once __DIR__ . '/ResultBody.php';
require_once __DIR__ . '/ResultHeaders.php';
require_once __DIR__ . '/TransformRequest.php';
require_once __DIR__ . '/TransformResponse.php';

RejectionReasonGeneratorUtility::setRegistrar(function (RejectionReasonGeneratorUtility $u): void {
    $u->clean = [RejectionReasonGeneratorClean::class, 'call'];
    $u->done = [RejectionReasonGeneratorDone::class, 'call'];
    $u->make_error = [RejectionReasonGeneratorMakeError::class, 'call'];
    $u->feature_add = [RejectionReasonGeneratorFeatureAdd::class, 'call'];
    $u->feature_hook = [RejectionReasonGeneratorFeatureHook::class, 'call'];
    $u->feature_init = [RejectionReasonGeneratorFeatureInit::class, 'call'];
    $u->fetcher = [RejectionReasonGeneratorFetcher::class, 'call'];
    $u->make_fetch_def = [RejectionReasonGeneratorMakeFetchDef::class, 'call'];
    $u->make_context = [RejectionReasonGeneratorMakeContext::class, 'call'];
    $u->make_options = [RejectionReasonGeneratorMakeOptions::class, 'call'];
    $u->make_request = [RejectionReasonGeneratorMakeRequest::class, 'call'];
    $u->make_response = [RejectionReasonGeneratorMakeResponse::class, 'call'];
    $u->make_result = [RejectionReasonGeneratorMakeResult::class, 'call'];
    $u->make_point = [RejectionReasonGeneratorMakePoint::class, 'call'];
    $u->make_spec = [RejectionReasonGeneratorMakeSpec::class, 'call'];
    $u->make_url = [RejectionReasonGeneratorMakeUrl::class, 'call'];
    $u->param = [RejectionReasonGeneratorParam::class, 'call'];
    $u->prepare_auth = [RejectionReasonGeneratorPrepareAuth::class, 'call'];
    $u->prepare_body = [RejectionReasonGeneratorPrepareBody::class, 'call'];
    $u->prepare_headers = [RejectionReasonGeneratorPrepareHeaders::class, 'call'];
    $u->prepare_method = [RejectionReasonGeneratorPrepareMethod::class, 'call'];
    $u->prepare_params = [RejectionReasonGeneratorPrepareParams::class, 'call'];
    $u->prepare_path = [RejectionReasonGeneratorPreparePath::class, 'call'];
    $u->prepare_query = [RejectionReasonGeneratorPrepareQuery::class, 'call'];
    $u->graphql_body = [RejectionReasonGeneratorGraphql::class, 'body'];
    $u->graphql_errors = [RejectionReasonGeneratorGraphql::class, 'errors'];
    $u->result_basic = [RejectionReasonGeneratorResultBasic::class, 'call'];
    $u->result_body = [RejectionReasonGeneratorResultBody::class, 'call'];
    $u->result_headers = [RejectionReasonGeneratorResultHeaders::class, 'call'];
    $u->transform_request = [RejectionReasonGeneratorTransformRequest::class, 'call'];
    $u->transform_response = [RejectionReasonGeneratorTransformResponse::class, 'call'];
});
